# Generated by Django 3.0.5 on 2020-05-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_auto_20200502_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('BG', 'Bungalo'), ('OF', 'Office'), ('DX', 'Duplex'), ('ST', 'Store'), ('LD', 'land')], default='BG', max_length=2),
        ),
    ]
