# Generated by Django 3.0.5 on 2020-05-02 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_auto_20200502_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='listing/listpics')),
                ('listingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.Listing')),
            ],
        ),
    ]
