# Generated by Django 3.0.5 on 2020-05-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_auto_20200502_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_status',
            field=models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale'), ('For Lease', 'For Lease')], default='FR', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Bungalo', 'Bungalo'), ('Office', 'Office'), ('Duplex', 'Duplex'), ('Store', 'Store'), ('Land', 'land')], default='BG', max_length=20),
        ),
    ]
