# Generated by Django 3.0.5 on 2020-05-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_auto_20200508_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='listing',
            new_name='listingid',
        ),
    ]
